// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Context.Component;

namespace Server.Context.Component.Migrations
{
    [DbContext(typeof(TModelContext))]
    [Migration("20181021143650_Component")]
    partial class Component
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Component.CategoryRelation", b =>
                {
                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Extension");

                    b.HasKey("Category");

                    b.ToTable("CategoryRelation");
                });

            modelBuilder.Entity("Server.Models.Component.ComponentDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.HasKey("Id");

                    b.ToTable("ComponentDescriptor");
                });

            modelBuilder.Entity("Server.Models.Component.ComponentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ComponentInfo");
                });

            modelBuilder.Entity("Server.Models.Component.ComponentRelation", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("ChildCategory");

                    b.Property<bool>("Locked");

                    b.Property<int>("ParentCategory");

                    b.Property<Guid>("ParentId");

                    b.Property<int>("PositionColumn");

                    b.Property<int>("PositionIndex");

                    b.Property<int>("PositionRow");

                    b.HasKey("ChildId");

                    b.ToTable("ComponentRelation");
                });

            modelBuilder.Entity("Server.Models.Component.ExtensionGeometry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PositionCol");

                    b.Property<int>("PositionRow");

                    b.Property<int>("SizeCols");

                    b.Property<int>("SizeRows");

                    b.HasKey("Id");

                    b.ToTable("ExtensionGeometry");
                });

            modelBuilder.Entity("Server.Models.Component.ExtensionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Distorted");

                    b.Property<int>("Height");

                    b.Property<byte[]>("Image");

                    b.Property<int>("Position");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("ExtensionImage");
                });

            modelBuilder.Entity("Server.Models.Component.ExtensionLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Height");

                    b.Property<string>("Style");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("ExtensionLayout");
                });

            modelBuilder.Entity("Server.Models.Component.ExtensionNode", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Locked");

                    b.Property<Guid>("ParentId");

                    b.Property<int>("Position");

                    b.HasKey("ChildId");

                    b.ToTable("ExtensionNode");
                });

            modelBuilder.Entity("Server.Models.Component.ExtensionText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption");

                    b.Property<bool>("Commit");

                    b.Property<string>("Description");

                    b.Property<string>("ExternalLink");

                    b.Property<string>("Footer");

                    b.Property<string>("FooterVisibility");

                    b.Property<string>("Header");

                    b.Property<string>("HeaderVisibility");

                    b.Property<string>("HtlmHeader");

                    b.Property<string>("HtmlFooter");

                    b.Property<string>("HtmlParagraph");

                    b.Property<string>("Paragraph");

                    b.HasKey("Id");

                    b.ToTable("ExtensionText");
                });
#pragma warning restore 612, 618
        }
    }
}
